name: CI

on:
  workflow_dispatch:
    inputs:
      EpCode:
        description: "Episode Number, {01..26}"
        required: true

env:
  EpNum: ${{ github.event.inputs.EpCode }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: "Transload MLB"
        run: |
          mkdir -p ~/job && cd ~/job/
          ./transload_mlb_S01.sh
