name: CI

on:
  workflow_dispatch:
    inputs:
      EpCode:
        description: "Episode Number, {01..26}"
        required: true

env:
  EpNum: ${{ github.event.inputs.EpCode }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Transload MLB"
        run: |
          chmod a+x ./transload_mlb_S01.sh
          ./transload_mlb_S01.sh
